# This workflow will install Python dependencies and run tests with a variety of Python versions

name: CI-ubuntu

on:
  push:
    branches: ['*']
    paths-ignore:         # Don't trigger on files that are updated by the CI
      - README.md    
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the package
      run: |       
        pip install .[test]        
    - name: Run test
      run: |
        python -m pseudopy.tests.test
